export default {
    "success" : true,
    "Data" : {
        "KeyWords" : [
            "Hiking",
            "Views",
            "Forest",
            "Wildlife",
            "Walking",
            "Easy",
            "Kid friendly",
            "Running",
            "Dogs on leash",
            "Wildflowers",
            "Short",
            "Moderately challenging",
            "Bird watching",
            "Long",
            "River",
            "Lake",
            "Mountain biking",
            "Challenging",
            "Camping",
            "No dogs",
            "Dog friendly",
            "Stroller friendly",
            "Backpacking",
            "Wheelchair friendly",
            "Paved",
            "Road biking",
            "Horseback riding",
            "Waterfall",
            "Snowshoeing",
            "Fishing",
            "Partially paved",
            "Historic site",
            "Beach",
            "Cross-country skiing",
            "City walk",
            "OHV/Off-road driving",
            "Paddle sports",
            "Cave",
            "Rails trails",
            "Rock climbing",
            "Scenic driving",
            "Bike touring",
            "Skiing",
            "Hot springs",
            "Event",
            "Pub walk",
            "Via ferrata"
        ]
    }
}
